---
# Ce rôle configure un site WordPress

##
# On défini la config d'Apache
##
- name: Apache config file for Wordpress
  template: src=wordpress.conf.j2 dest=/etc/httpd/conf.d/wordpress.conf
  notify: restart httpd


