---

# Création du répertoire /usr/share/picocms
- name: Création du répertoire /usr/share/picocms
  file: path=/usr/share/picocms state=directory

# Installation des sources de Pico depuis GitHub
- unarchive: src=https://github.com/picocms/Pico/releases/download/v1.0.3/pico-release-v1.0.3.tar.gz dest=/usr/share/picocms copy=no force=yes
  environment: { http_proxy: "http://FLX_DEVLABS:FLX_DEVLABS@proxy1.mousquetaires.com:8080", https_proxy: "http://FLX_DEVLABS:FLX_DEVLABS@proxy1.mousquetaires.com:8080" }

# Définition du fichier de conf Apache.
- name: Ajouter le fichier /etc/httpd/conf.d/picocms.conf
  template: src=picocms.conf.j2 dest=/etc/httpd/conf.d/picocms.conf
  notify: 
   - restart httpd

