---
##
# Mise en oeuvre de MySQL / MariaDB 
##
- name: Installer Mysql/MariaDB
  yum: name=mariadb-server-5.5* state=present

- name: Installer Mysql-python pour changer le pass du user root
  yum: name=MySQL-python state=present

- name: Start Mysql Service
  service: name=mariadb state=started enabled=yes

- name: Remplacer le fichier de config Mysql
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify: 
  - restart mariadb

- name: update mysql root password for one root
  mysql_user: name=root host=localhost password={{ mysql_root_password }}

- name: copy .my.cnf file with root password credentials
  template: src=.my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600

- name: update mysql root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ mysql_root_password }} priv=*.*:ALL,GRANT state=present
  with_items:
   - '%'
   - 127.0.0.1
   - ::1
   - localhost
   - "{{ ansible_fqdn }}"

#- name: ensure anonymous users are not in the database
#  mysql_user: name='' host={{ item }} state=absent
#  with_items:
#   - '%'
#   - 127.0.0.1
#   - ::1
#   - localhost
#   - "{{ ansible_fqdn }}"

- name: remove the test database
  mysql_db: name=test state=absent

